name: Conventional Changelog Action
description: Automatically generate a changelog since the last tag, using the conventional commit format
inputs:
  token:
    description: Github repository token
    required: true
  exclude:
    description: Which commit types to exclude, comma separated string
    required: false
outputs:
  changelog:
    description: Generated changelog for the latest tag
  changes:
    description: Generated changelog for the latest tag, without the version/date header
runs:
  using: node12
  main: "dist/index.js"