name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Locally
        uses: actions/checkout@v2
        if: ${{ env.ACT }}
        with:
          path: "tag-changelog"
      - name: Checkout GitHub
        uses: actions/checkout@v2
        if: ${{ !env.ACT }}

      - name: Create changelog
        id: changelog
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude: chore

      - name: Create release
        uses: actions/create-release@latest
        if: ${{ !env.ACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}

      - name: Read CHANGELOG.md
        id: readfile
        uses: juliangruber/read-file-action@v1
        if: ${{ !env.ACT }}
        with:
          path: ./CHANGELOG.md

      - name: Write to CHANGELOG.md
        uses: DamianReeves/write-file-action@master
        if: ${{ !env.ACT }}
        with:
          path: ./CHANGELOG.md
          contents: ${{ steps.changelog.outputs.changelog }}${{ steps.readfile.outputs.content }}
          write-mode: overwrite

      - name: Commit and push CHANGELOG.md
        uses: EndBug/add-and-commit@v7
        if: ${{ !env.ACT }}
        with:
          add: CHANGELOG.md
          message: "chore: Update CHANGELOG.md"
          branch: main