name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Locally
        uses: actions/checkout@v2
        if: ${{ env.ACT }}
        with:
          path: "conventional-changelog-action"
      - name: Checkout GitHub
        uses: actions/checkout@v2
        if: ${{ !env.ACT }}
      - name: Create changelog
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
